### ISSUE TITLE
Not compatible with Project Lombok.

### ISSUE THREAD

**Issue by rupeshsasne** [bluelinelabs/LoganSquare#161]
In my model class there are too many `private` fields, and for their `getters` and `setters` I use `Lombok`, which generates the same at `compile time`, I guess those are not available while LoganSquare is processing the model class, so it is asking me to convert those private fields to public fields.. which can not be done.. any workaround?

**Comment by mannodermaus** [comment]
It's sufficient for LoganSquare if annotated fields are package-private. Rather than making them all public, would that be a reasonable alternative for you?

**Comment by rupeshsasne** [comment]
ummm.. sounds reasonable.. but this is certainly not a concrete solution, right?

**Comment by mannodermaus** [comment]
I'd say go for it, since tweaking the library's core & processor to gain compatibility with the complex code generated by Lombok would be a more involved endeavor than using package-visibility on your model's fields. It works for all of my projects, since models are usually stashed away in their own package anyways, so the loosened visibility doesn't hurt!

**Comment by rupeshsasne** [comment]
I agree.. thanks.. :+1:
