### ISSUE TITLE
Adding the ability to create multiple instance of the LoganSquare object

### ISSUE THREAD

**Issue by fred8** [bluelinelabs/LoganSquare#18]
A nice feature of GSON is to be able to register different type of adapter on different instance of the Gson object. -- For some obvious performance reason, the app have to keep a singleton of the created object but could be quickly done by a factory pattern.

Essentially that help when you need to deserialize / serialize an object in a different way.
What do you think?

**Comment by EricKuck** [comment]
GSON can do this because it handles everything at runtime. This library does all its magic at compile-time, which means it would have to somehow generate classes that provide multiple ways to parse/serialize a single object, then allow you to pick which one you want.

I've personally never seen a reason to do something like this. Do you have a real-world example of a time where it could be useful? I'm having trouble picturing a reason you'd want to parse or serialize a single object type different ways. Seeing an example would help me get a better understanding for the use case.

**Comment by EricKuck** [comment]
Haven't heard back, so I'll go ahead and close this. I'd be happy to re-open if you want to continue discussing.
