### ISSUE TITLE
Read map of objects

### ISSUE THREAD

**Issue by skywave** [bluelinelabs/LoganSquare#23]
I noticed a lack of support to deserialize maps, as i was trying to parse the following input
```json
{ "journey1" : { } , 
  "journey2" : { }
}
```

to 
```java
HashMap<String,V0Journey>
```

**Comment by EricKuck** [comment]
Maps are fully supported. What issue are you having exactly? Can you post the generated code?

**Comment by skywave** [comment]
It works when the HashMap is a member of a Class, but i'm trying to deserialize a map as the root-object. Much in the way there is a seperate parseList, because of the parameterization of the List (?)

**Comment by EricKuck** [comment]
The parseList and serialize (from list) methods exist because sometimes APIs use a JSON array as the root rather than a JSON object. In your case, you already have an object as the root, so why not parse it as an object instead of a map? Seems like much better OOP to me. 

If there's a legit need for something like this I'm not opposed to adding it. I'm just struggling to see how parsing to/serializing from a map is anything but a workaround for creating proper Java models.

**Comment by skywave** [comment]
If the JSON object has variable keys (based on the content), it's not possible to make such a map an object.

**Comment by EricKuck** [comment]
True, but if it had variable keys how could you ever use it in code? Isn't that exactly what JSON arrays were created for? An example of a real-world scenario where this happens would be very helpful.

**Comment by skywave** [comment]
I admit it's a somewhat retardistic API design yes, but GSON for example supports it. In the end you can just iterate over all the entries.
This is one real-world example http://v0.ovapi.nl/line/CXX_M300_2,CXX_M300_1 where the id's requested in the URL actually turn up in the result.

**Comment by EricKuck** [comment]
I guess I'll add it in, since app developers usually can't control whether or not the API they're using follows common standards. I'm just hoping people don't abuse it as a shortcut for actually creating proper  models. Can't tell you how many times I've seen code that does something like this: jsonMap.get("model").get("submodel").get("title") with absolutely no error handling around it whatsoever. Makes me cringe.

**Comment by EricKuck** [comment]
Support for this has been added to v1.0.5, which has just been pushed to JCenter and Maven Central.
