### ISSUE TITLE
java.lang.Boolean fields should be nullable

### ISSUE THREAD

**Issue by talklittle** [bluelinelabs/LoganSquare#26]
The generated JSON parser code uses `Boolean.valueOf(jsonParser.getValueAsBoolean())` for `java.lang.Boolean` fields. However, `jsonParser.getValueAsBoolean()` defaults to `false` when the value is null.

**Comment by EricKuck** [comment]
Not sure what the proper etiquette is here regarding accepting pull requests. What you did fixes the issue perfectly, but I just reworked the way what you changed works. I'm going to take your suggestion and add it for parsing Boolean, Integer, Long, Float, and Double objects, but it'll be in a different form because of the stuff I'd already changed.

Is the proper etiquette to accept your pull request, then change it all, so you get credit for the fix? Or should I just close it and commit what I already changed, but with your idea included?

**Comment by talklittle** [comment]
@EricKuck Hey thanks for being so courteous. I'll close the PR if you've already implemented a better fix.

**Comment by EricKuck** [comment]
What I did is by no means "better," just different. I had already changed some of that code locally to better utilize some of JavaPoet's features for cleaner generated code, so your PR wouldn't have merged in correctly. Thanks for understanding. I don't want to try to take all the credit for stuff, but I also don't want to have commits that immediately get overwritten, so I wasn't too sure what to do.

In case you're curious what the changes were, I just merged them in here: 0e90af9b413d97159d34d54890886c99590ec397
