### ISSUE TITLE
Add support for alternative JSON [de/]serializers

### ISSUE THREAD

**Issue by jasta** [bluelinelabs/LoganSquare#29]
A hard dependency on Jackson makes this project difficult to adopt in existing large projects or ones that are sensitive to dependencies.  In particular, an option to use Android's built-in `JsonReader` parser would be very handy.

A modular design that allowed custom code generators (or sufficient hooking in the standard generator) would be greatly preferred as it is technically possible to build a custom JSON parser that will outperform Jackson for your particular use case.  Specifically, Jackson creates many internal unnecessary objects because it doesn't have strong awareness of what concrete target type the JSON type is going to fit into.  With this knowledge in the parser generator, primitives (including strings) can be constructed with less object overhead.

**Comment by EricKuck** [comment]
You're thinking of Jackson Databind, not the Jackson streaming API, which is what this library uses. There is absolutely no way that using Android's JsonReader could even come close to being as fast as this. Also, including only the Jackson streaming API as a dependency is much smaller than you think (~230kb as a jar, even smaller when compiled into your app). You're probably used to using Jackson core + Jackson annotations + Jackson databind, which can be pretty big.

The purpose of this library is to generate the fastest possible JSON parsing/serializing code with almost no additional effort from the app developer, and using the Jackson streaming API is the best way to do that at the moment. We're very happy with our decision and will not be changing that until something faster comes along.

**Comment by jasta** [comment]
I was referring to the streaming core.  It is inappropriate to require this
dependency in third party libraries.  For instance, does Retrofit require
Jackson?  No, that would be a problematic requirement.  Instead, it offers
a way to use Jackson conveniently along with other engines.

I understand the design motivation but I cannot use this library as-is
because I can't require Jackson in users of my library.

**Comment by EricKuck** [comment]
I would suggest reading up on what Jackson core is. It doesn't map objects at all like you seem to think it does. What you said about creating unnecessary internal objects because of not knowing the concrete type is only true of Databind.

Regardless, this library generates code to serialize and parse your objects for you. To do that, it has to target a JSON library. Making it work with another system would pretty much require forking it and rewriting the majority of the code. This isn't a runtime library like Retrofit, so the comparison doesn't fit.

If you're that concerned about the tiny amount of space Jackson will take up and don't care about performance, then it sounds like this isn't the library for you.
