### ISSUE TITLE
Support standartized annotations

### ISSUE THREAD

**Issue by Alexander--** [bluelinelabs/LoganSquare#39]
Thanks for creating such awesome library! It would have been even better if it had at least partial support for some standardized annotations (such as Jax-Rs 2 bean annotations). Such support would greatly increase interoperability and make using it in existing projects much less of hassle.

**Comment by EricKuck** [comment]
Those annotations don't really cover all of the use cases of this library, and definitely wouldn't cover future use-cases. Trying to use anyone else's annotations would really cripple our ability to add anything new. What would the benefit of supporting for these be, besides saving developers ~2 minutes of annotating their models?

**Comment by Alexander--** [comment]
> Those annotations don't really cover all of the use cases of this library, and definitely wouldn't cover future use-cases.

It is totally fine to promote your own annotations, but there should be no harm from providing subset of full functionality, supported by other annotation types. Besides, adding check for couple of other annotation types is ~2 minutes of work for you as well.

**Comment by EricKuck** [comment]
It's true that it's not much more work to add support for other annotations, but I also don't want to promote people using only a subset of the library because they don't want to take the time to use the proper annotations. The annotations included are part of this library and really aren't hard to use at all. They've been thought through pretty well and trying to bolt on support for something that wasn't written for that purpose just wouldn't do this library justice.

Also, I don't think anyone it's considered at all standard to support other people's annotations. Jackson doesn't support GSON annotations, GSON doesn't support JAX-RS annotations, and so on. Personally, I don't think it should be any different for LoganSquare.
