### ISSUE TITLE
Question: Is is possible to parse/serialize to/from java.util.Map?

### ISSUE THREAD

**Issue by hideki** [bluelinelabs/LoganSquare#48]
Hi,

I'd like to serialize/parse between java.util.Map and  JSON string. And following codes don't work because I did not set annotations. Is is possible to parse/serialize to/from java.util.Map? If yes, how can I do it?

Serialize
```
Map<String, Object> map = new HashMap<String,Object>();
map.put("key", 1);
String json = LoganSquare.serialize(map);
```

Parse
```
String json = "{\"key\":1}";
Map<String, Object> map = LoganSquare.parse(json, Map.class);
```

Thanks,

**Comment by EricKuck** [comment]
The reason for this library's existence is to help developers create proper models and stick to good OOP practices, and to have those models parse extremely quickly. Since parsing/serializting directly to/from a dictionary is exactly what this library is trying to help developers get away from, it will not be supported at any time.

**Comment by hideki** [comment]
@EricKuck Thank you for your response!
