### ISSUE TITLE
LoganSquare doesn't throw any exception while deserializing wrong JSON.

### ISSUE THREAD

**Issue by ravikumar-n** [bluelinelabs/LoganSquare#64]
I'm writing [unit tests](https://github.com/ravikumar-n/retrofit/blob/master/retrofit-converters/logansquare/src/test/java/retrofit/converter/LoganSquareConverterTest.java) for Retrofit-LoganSquareConverter module.  The below test case to demonstrate `LoganSquare.parse()` failure on invalid JSON input fails:

``` 
@Test
  public void deserializeWrongValue() throws Exception {
    ResponseBody body = ResponseBody.create(MEDIA_TYPE, "{\"foo\":\"bar\"}");
    try {
      converter.fromBody(body, MyObject.class);
      fail();
    } catch (Exception ignored) {
    }
  }
```
The input JSON and object parameters doesn't match at all, but on deserializing LoganSquare instead of throwing an Exception, creates the object with fields initialized to null.

```
MyObject obj = (MyObject)converter.fromBody(body, MyObject.class);
System.out.println("Message: "+obj.getMessage() + " Count: "+obj.getCount());
```
Outputs:
```
Message: null Count: 0
```

 I'm not sure this is a bug or feature?

**Comment by EricKuck** [comment]
It's not a bug or a feature. It's how JSON parsing should work. If the JSON parser throws an exception when the JSON and your model don't match up, apps would start crashing when APIs got updated. Why would this be something desirable?

**Comment by ravikumar-n** [comment]
@EricKuck If few params doesn't match with the model it's acceptable, but consider the entire response doesn't match at all, it's better to throw exception or return null value.

I'm able to find the scenario where the above mentioned issue occurs. When I call `LoganSquare.parse` with input param as string/stream directly without using Retrofit, I get myObject as null.

```
Object myObject = LoganSquare.parse(WRONG_JSON, MyObject.class); //passing data as a string
//myObject is null
```
or

```
InputStream stream = new ByteArrayInputStream(WRONG_JSON.getBytes(StandardCharsets.UTF_8)); //passing as a InputStream
MyObject myObject = LoganSquare.parse(stream, MyObject.class);
//myObject is null
```
But when I combine LoganSquare with RetroFit, it creates the myObject with default values.

**MyObject$$JsonObjectMapper.java**:
```
 public static MyObject _parse(JsonParser jsonParser) throws IOException {
    MyObject instance = new MyObject();
    if (jsonParser.getCurrentToken() == null) {
      jsonParser.nextToken();
    }
    if (jsonParser.getCurrentToken() != JsonToken.START_OBJECT) {
      jsonParser.skipChildren();
      return null;
    }
    while (jsonParser.nextToken() != JsonToken.END_OBJECT) {
      String fieldName = jsonParser.getCurrentName();
      jsonParser.nextToken();
      parseField(instance, fieldName, jsonParser);
      jsonParser.skipChildren();
    }
    return instance;
  }
```
The following code block is not executed at all, that's the reason I'm getting myObject with default values but it's executed for the first two calls i.e without using RetroFit.
```
if (jsonParser.getCurrentToken() != JsonToken.START_OBJECT) {
      jsonParser.skipChildren();
      return null;
    }
```
Do you have any suggestions to resolve the problem?

**Comment by EricKuck** [comment]
In my opinion, it's up to the developer to make sure they're parsing the data to the correct type. Throwing an exception that could crash someone's app is an unacceptable solution. What would be the cutoff on the JSON being right vs. wrong? All fields have to match? Half of the fields match? At least one has to match? It's totally subjective, which is why I'm much more comfortable just leaving it up to the developer.

Can you post what WRONG_JSON from your example is set to? If it's returning null, that's likely because it's actually invalid JSON, not just the wrong type of object. That if statement is simply checking to see if the object starts with an opening curly brace.

**Comment by ravikumar-n** [comment]
Sorry my bad, I had used the WRONG_JSON value. The behavior of LoganSquare doesn't change when combined with/without Retrofit. 

Consider the following scenario:
**LoganSquareConverterTest.java**
```
 @Test
  public void deserializeWrongValue() throws Exception {
    ResponseBody body = ResponseBody.create(MEDIA_TYPE, "{\"foo\":\"bar\"}");
    try {
      converter.fromBody(body, MyObject.class);
      fail(); //Unit test fails here
    } catch (Exception ignored) {
    }
  }
```
I need `fail()` statement,  Jake Wharton had pointed me to include it for the LoganSquareCoverter pull request.  When I introduce `fail()`, the test fails, but other [retrofit converters](https://github.com/square/retrofit/tree/master/retrofit-converters) like`JackSonConverter` throws exception for the same scenario.

>What would be the cutoff on the JSON being right vs. wrong? All fields have to match? Half of the fields match? At least one has to match? It's totally subjective, which is why I'm much more comfortable just leaving it up to the developer.

How can I get Test result as **pass** for the above mentioned scenario ?.

**Comment by EricKuck** [comment]
So I looked through the pull request. First of all, thanks for doing this! Much appreciated.

Second, I think his comment was actually that you need to `fail()` within the catch block, like so:

```
@Test
public void deserializeWrongValue() throws Exception {
    ResponseBody body = ResponseBody.create(MEDIA_TYPE, "{\"foo\":\"bar\"}");
    try {
        converter.fromBody(body, MyObject.class);
    } catch (Exception ignored) {
        fail();
    }
}
```

Also, I'm not sure if you even need the `deserializeWrongValue()` method. I see that the Jackson converter has this method, due to the fact that Jackson is more willing to crash an app than to handle unexpected JSON. If you look at the GSON converter's test though, it isn't there. I'd probably recommend adding `fail()` to all of your catch blocks and simply removing the `deserializeWrongValue()` method altogether.

**Comment by JakeWharton** [comment]
You never need `fail()` in a `catch` block, you would just remove the try/catch and let the exception fail the test. If you are testing that a piece of code throws when executed, you want `fail()` at the end of the `try` block to ensure that a regression to the lack of throwing an exception is a failure.

**Comment by EricKuck** [comment]
@JakeWharton good call. Wasn't really looking at the syntax that much, just trying to quickly interpret what you meant. Just ignore me :)

@ravikumar-n Still seems like you could just remove this test, right? This library wasn't written in such a way that that test would ever pass, and (at least to me) it doesn't seem necessary at all.

**Comment by ravikumar-n** [comment]
> it doesn't seem necessary at all.
I differ with you. 

**Scenario 1**:
User->Login Request->Wrong_JSON>Exception>{Handle it and display a Toast indicating the issue} 
**Scenario 2**:
User->Login Request->Wrong_JSON>ResponseObject 

1. Now how do I handle the second scenario? 
2. How do I make sure, I have the server response mapped as the ResponseObject but not the ResponseObject with default values?
3. What if server response and default object values are same?

**Comment by EricKuck** [comment]
Again, to me it's up to the developer to know the API they're using and what kind of objects will be returned. The only time it would ever be valid for an API to return different JSON objects for one endpoint is when there's also a different status code (ie 200 returns a LoginResponse, whereas 4xx returns ErrorResponse or something like that). This can be handled very easily in your networking code (where it belongs) rather than in your JSON parsing code.

I do not believe that it should be on the JSON parsing library to determine what kind of object was supposed to be parsed. Like I said before, whether a JSON object is the "right" or "wrong" type is totally subjective and will depend entirely on the developer's specific implementation.

Regarding the defaults, they're just the the standard Java defaults, so `null` for objects, false for booleans, and 0 for ints, floats, etc. 

If you did have some kind of crazy API that just returned whatever kind of JSON object it wanted with 200 status codes, I would probably handle it with something like this (but seriously, this should never, ever happen):

```
LoginResponse response = LoganSquare.parse(jsonStream, LoginResponse.class);
if (response.username != null) {
    // API returned the right type. Do whatever you're going to do with it.
} else {
    // API somehow returned the wrong type. Display a snackbar, toast, dialog, etc.
}
```

**Comment by ravikumar-n** [comment]
Cool, I'd just gave an example for the sample scenario(Of-course it's crazy API).
Thanks for the explanation :+1:

**Comment by EricKuck** [comment]
Great, hopefully that will fit your needs. Regarding my comment that you quoted earlier ("it doesn't seem necessary at all"), I was referring to the actual test in your converter implementation. This library wasn't meant to handle that situation in a way that would throw an exception, so the test itself isn't necessary. Given the fact that it isn't present in the GSON converter's tests, as GSON doesn't throw an exception in this case either, I'm sure you'd be fine just removing it altogether.

**Comment by glenaries03** [comment]
Hi I'm new to logansquare and having problem parsing this 

{ "Test":
    {
        "slNo": 1,
        "name": "abc",
        "contactNo": 123456
    }
}

and this is my model

@JsonObject
public class User {

    @JsonObject
    public static class Test{

        @JsonField(name="slNo")
        public Integer slNo;

        @JsonField(name="name")
        public String name;

        @JsonField(name="contactNo")
        public String contactNo;
    }
}

What am i doing wrong? TIA
