### ISSUE TITLE
Model with nested class

### ISSUE THREAD

**Issue by willyanto** [bluelinelabs/LoganSquare#84]
I have Model
```
package com.example.Model;

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

@JsonObject
public class MDeposit extends MBase {
    @JsonField
    private ArrayList<Deposit> list;

    public ArrayList<Deposit> getList() {
        return list;
    }

    public void setList(ArrayList<Deposit> list) {
        this.list = list;
    }

    @JsonObject
    public class Deposit{
        @JsonField
        private int id;

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }
    }
}
```

But I Deposit class cannot recognized and get this error in MDeposit$$JsonObjectMapper.java
``` 
Error:(7, 25) error: cannot find symbol class Model
 ```
Any solution with this problem?

**Comment by markrietveld** [comment]
@willyanto Your inner class should be `static`

**Comment by willyanto** [comment]
@markrietveld Still same problem

Error on import com.example.Model in generated file MDeposit$$JsonObjectMapper.java

**Comment by EricKuck** [comment]
I can look into fixing this, but the issue is caused because your package name is invalid. According to Oracle's docs (http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html):

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.

**Comment by idulnyavka** [comment]
Is package naming the root cause of the issue? That's really weird.
I got a projects for support with established structure that I cannot easily update, and I added LoganSquare support for object and list of objects. 
But now, I cannot get it to work with object i object (object as a field on another one).

I'm using v. 1.3.6 and getting compiler exceptions:

```
D:\Projects\blablabla\build\generated\source\apt\AppName\debug\com\clientname\mainSDK\Models\Contacts\ContactsGroup$$JsonObjectMapper.java
Error:(8, 28) error: cannot find symbol class Models
Error:(18, 50) error: package Models.Contacts does not exist
```

Class declaration with issue is as follows:

```

@JsonObject
public class ContactsGroup {

    @JsonField(name = "GroupPK")
    private long _id;
    @JsonField
    private long MainFK;
    @JsonField(name = "GroupName")
    private String _name;
    @JsonField
    private String GroupDescr;
    @JsonField(name = "Contacts")
    private ArrayList<PhoneBookContact> _contacts;

//...
}
```

PhoneBookContact class is annotated with @JsonObject and works fine as a single class and as an array.
Failed as nested in another class.

What are any steps? Can I handle this without lots of packages renaming?

Thanks

**Comment by idulnyavka** [comment]
Okay, even this is the craziest thing, it got fixed by local renaming (still not committing it to source control).
Can this be fixed other way than renaming all packages and handling all the outcome?
