### ISSUE TITLE
Support for generic base classes

### ISSUE THREAD

**Issue by cesar1000** [bluelinelabs/LoganSquare#96]
Hi,

We are using LoganSquare to parse model objects, and we are using a ModelObjectProvider<T> interface to declare that a certain json object can provide a model object. For example:

```java
@JsonObject
class JsonEntity extends ModelObjectProvider<Entity> {
    @JsonField
    int start;
    @JsonField
    int end;

    @Override
    @NotNull
    public Entity toModelObject() {
        return new Entity(this.start, this.end);
    }
}
```

This is working as expected, and we have built a powerful collection of utilities that use type converters for parsing model objects automatically. For object hierarchies, we'd like to do something like this:

```java
@JsonObject
class abstract JsonEntity<E extends Entity> extends ModelObjectProvider<E> {
    @JsonField
    int start;
    @JsonField
    int end;
}

@JsonObject
class JsonHashtagEntity extends JsonEntity<HashtagEntity> {
    @JsonField
    String text;

    @Override
    @NotNull
    public HashtagEntity toModelObject() {
        return new HashtagEntity(this.start, this.end, this.text);
    }
}
```

However, this doesn't work: LoganSquare does not support generic classes, even if none of the fields has a generic type. Removing @JsonObject from the base class doesn't work either, since @JsonField is only allowed in a @JsonObject class. It would be awesome if you could remove the generic class restriction when all fields have concrete types, since it doesn't seem to be strictly required.

I find LoganSquare is extremely powerful, but it falls short at providing the tools for mapping LoganSquare objects to application model objects, and this is one of the problems we have run into. I'll file a separate ticket about parsing collections in the desired format. I'll be happy to hear about your recommendations!

**Comment by EricKuck** [comment]
@cesar1000 I've actually been working on proper generic class support on the DL for a while now. It's mostly working, but there are still some edge cases that aren't totally handled yet. If all goes well, I'm hoping to have that wrapped up by the end of the week. I'll let you know when it's done.

**Comment by EricKuck** [comment]
@cesar1000 This should now be working in v1.2.0. Haven't had time to update the readme yet, but here's how you'd use it (assuming you're using `InputStream`s and `OutputStream`s):

`LoganSquare.parse(is, new ParameterizedType<JsonEntity<HashtagEntity>>() { })`

and 

`LoganSquare.serialize(object, new ParameterizedType<JsonEntity<HashtagEntity>>() { }, os);`

In the case of your `JsonHashtagEntity` above, you could use the library exactly how you've always used it without using these new methods.

One thing to note is that, due to Java's type erasure, some reflection is necessary in order to handle generics. While LoganSquare is still extremely performant with generics in comparison to other JSON parsing libraries, any class that uses generics will be inherently slower to parse and serialize than one that doesn't. The performance hit occurs during initialization, so once everything is configured, it should be as fast as you're used to.

Let me know if you run into any issues!
